version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - ./backend/test.db:/app/backend/test.db  # Монтируем файл базы данных в контейнер
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

networks:
  dev:
